name: Laravel Deploy Preview
description: Deploy a PR preview site.
inputs:
  forge-token:
    description: Laravel Forge API token.
    required: true
  github-token:
    description: GitHub token to create an authenticated Octokit client.
    required: false
    default: ${{ github.token }}
  servers:
    description: 'List of Forge servers to use for deploy previews. Each line must contain a domain name and a Forge server ID separated by a space. Note: currently only supports a single server.'
    required: true
  after-deploy:
    # 'post-deploy'? 'command'?
    description: Shell script to append and run after the default Forge deploy script. E.g. `npm ci && npm run build`.
    required: false
  env-file:
    description: env file to be merged with the project's environment.
    required: false
runs:
  using: node16
  main: dist/index.js
